# https://taskfile.dev

version: "3"

env:
  CONTAINER_BIN: 'docker'
  DEPLOYMENT_ENVIRO: '{{.DEPLOYMENT_ENVIRO | default ""}}'
  HTTP_PROXY: '{{.HTTP_PROXY | default ""}}'
  HTTPS_PROXY: '{{.HTTPS_PROXY | default ""}}'

  ACCESS_TOKEN: "$(cat ~/.appdat/images/SSMO_IMAGES)"
  ACCESS_USER: '{{.USER | default "unknown"}}'
  CREDS: '{{.ACCESS_USER}}:{{.ACCESS_TOKEN}}'

  DOCKER_GATEWAY_HOST: "192.168.65.254"

  IMAGE_VERSION: '{{.IMAGE_VERSION | default "k8s"}}'

vars:
  REGISTRY: localhost:5005
  IMAGE_NAME: k8s
  IMAGE_TAG: "{{.IMAGE_VERSION}}"
  IMAGE: "{{.IMAGE_NAME}}:{{.IMAGE_TAG}}"
  CONTAINER_NAME: "{{.IMAGE_NAME}}"

tasks:
  default:
    desc: Shows this help message
    cmds:
      - task --list-all

  build:
    desc: Build k8S
    cmds:
      - |
        ${CONTAINER_BIN} build --file ./docker/Dockerfile --tag "{{.IMAGE}}" .

  start:
    desc: Start k8s
    deps:
      - build
    cmds:
      - cmd: task stop
        ignore_error: true
      - |
        ${CONTAINER_BIN} run -d --rm \
          --privileged=true \
          --volume ${PWD}/downloads:/downloads \
          --volume ${PWD}/tools:/tools \
          --name {{.CONTAINER_NAME}} {{.IMAGE}}

  logs:
    - cmd: ${CONTAINER_BIN} logs --follow {{.CONTAINER_NAME}}
      ignore_error: true

  shell:
    desc: shell into running container
    cmds:
      - cmd: ${CONTAINER_BIN} exec -it {{.CONTAINER_NAME}} bash

  stop:
    desc: Stop RHEL
    cmds:
      - ${CONTAINER_BIN} rm -f {{.CONTAINER_NAME}}

  clean:
    desc: Clean RHEL
    cmds:
      - ${CONTAINER_BIN} image rm -f {{.IMAGE}} 2>/dev/null || true
